version: '3.2'

services:
  pipcache:
    image: ${IMAGE_REPO}:latest
    container_name: pipcache
    build:
      context: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:3141:3141"
    volumes:
      - $PWD/config:/config
      - pip-cache:/data
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1024M
        reservations:
          cpus: "2"
          memory: 500M
#    entrypoint: /bin/sh
#    stdin_open: true
#    tty: true
volumes:
  pip-cache:
