version: '3.2'

services:
  pipcache:
    image: ${IMAGE_REPO}:latest
    container_name: pipcache
    build:
      context: .

      labels:
        Vendor: "LiveU"
        Commit: ${CI_COMMIT_DESC}
    restart: unless-stopped
    ports:
      - 3141:3141
    volumes:
      - $PWD/config:/config
      - /Volumes/extDisk/pipcache:/data
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
